# Generated by Django 4.2.5 on 2023-09-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title2', models.CharField(blank=True, max_length=500)),
                ('title3', models.CharField(blank=True, max_length=500)),
                ('creator', models.CharField(max_length=500)),
                ('creator2', models.CharField(blank=True, max_length=500)),
                ('creator3', models.CharField(blank=True, max_length=500)),
                ('source', models.URLField()),
                ('source2', models.URLField(blank=True)),
                ('source3', models.URLField(blank=True)),
                ('license', models.CharField(max_length=500)),
                ('license2', models.CharField(blank=True, max_length=500)),
                ('license3', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='attributions/images/')),
                ('image2', models.ImageField(blank=True, upload_to='attributions/images/')),
                ('image3', models.ImageField(blank=True, upload_to='attributions/images/')),
            ],
        ),
    ]
